server:
  port: 8888    #server 端口

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/master?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=GMT
    username: root
    password: itcast
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource            #alibaba连接池
    druid:
      initial-size: 10                                      #初始化建立10条链接
      max-active: 30                                        #最多二十条
      min-idle: 5                                           #最小连接数量
      max-wait: 60000                                       #获取连接时最大等待时间
      time-between-eviction-runs-millis: 60000              #连接有效性检测时间
      min-evictable-idle-time-millis: 300000                #连接在池中最小生存的时间
      max-evictable-idle-time-millis: 900000                #连接在池中最大生存的时间
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1                            #检测连接是否有效
      webStatFilter:                                        #配置监控统计
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          log-slow-sql: true                                #记录慢SQL
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      aop-patterns: com.zf1976.app.*.controller.*

  profiles:                                                 #加载配置文件
    active: conf,log,dev

  devtools:                                                 #热部署
    restart:
       enabled: true

  mail:                                                     #邮件默认配置
    default-encoding: UTF-8
    host: smtp.qq.com
    password: mwkvuwzspcvjibab
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    username: 1596863112@qq.com

  jackson:                                                  #json序列化配置
    time-zone: GMT+8
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:                                                  #servlet配置
    multipart:
      enabled: true

  thymeleaf:                                                #thymeleaf模版
    suffix: .html

mybatis-plus:                                               #mybatis-plus 配置
  global-config:
    db-config:
      update-strategy: ignored
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*Dao.xml
  check-config-location: true
  type-enums-package: com.zf1976.ant.upms.biz.pojo.enums,com.zf1976.ant.common.log.pojo.enums

#文件路径配置
file:
  config:
    # 工作文件
    work-file-path: /work
    # 普通文件大小/M
    file-max-size: 50
    # 头像大小
    avatar-max-size: 10
    #请求相对路径
    relative:
      avatar-url: /avatar/**
      file-url: /file/**
    #实际路径（不完整）
    real:
      avatar-path: /avatar/
      file-path: /file/
