## ci/cd from the finished product
version: "3"

services:

  mayi-upms-biz:
    container_name: mayi-upms-biz
    restart: always
    ports:
      - "7777:5555"
      - "5555:5555"
    build:
      context: ./
      dockerfile: docker/prod/system/Dockerfile
    image: mayi-upms-biz
    depends_on:
      - mayi-nacos
      - mayi-mysql
      - mayi-redis
    hostname: mayi.upms.biz

  mayi-auth:
    container_name: mayi-auth
    restart: always
    ports:
      - "9000:9000"
      - "6666:6666"
    build:
      context: ./
      dockerfile: docker/prod/auth/Dockerfile
    image: mayi-auth
    depends_on:
      - mayi-nacos
      - mayi-redis
    hostname: mayi.auth

  mayi-gateway:
    container_name: mayi-gateway
    restart: always
    ports:
      - "8888:8888"
    build:
      context: ./
      dockerfile: docker/prod/gateway/Dockerfile
    image: mayi-gateway
    depends_on:
      - mayi-nacos
      - mayi-redis
    hostname: mayi.gateway

  mayi-admin-monitor:
    container_name: mayi-visual-admin
    ports:
      - "4444:4444"
    build:
      context: ./
      dockerfile: docker/prod/monitor/Dockerfile
    image: mayi-admin-monitor
    hostname: mayi.visual.admin

  mayi-redis:
    container_name: mayi-redis
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"
    hostname: mayi.redis

  mayi-mysql:
    container_name: mayi-mysql
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: itcast
    security_opt:
      - seccomp:unconfined
    image: mayi-mysql
    ports:
      - "3306:3306"
    hostname: mayi.mysql

  mayi-nacos:
    container_name: mayi-nacos
    image: nacos/nacos-server
    restart: always
    environment:
      - "MODE=standalone"
    ports:
      - "8848:8848"
    depends_on:
      - mayi-mysql
    hostname: mayi.nacos
