# 公用captcha配置
verify-code:
  #  登录图形验证码有效时间/分钟
  expiration: 2
  #  验证码高度
  width: 111
  #  验证码宽度
  heigth: 36
  # 内容长度
  length: 2
  # 字体名称，为空则使用默认字体
  font-name:
  # 字体大小
  font-size: 25
  #  验证码类型配置
  code-type: arithmetic
  # 验证码
  key-prefix: captcha-

#公用safe jwt session 等配置信息
security:
  #管理员名字 自己配置就好了/前端也需要修改。。
  owner: admin
  #token 头
  token-header: ANT-ADMIN
  # 签发方
  token-issuer: Ant
  # 是否限制单用户登录
  token-single: true
  # authorities key
  token-authorities-key: authorities
  # token前缀 根据自己喜好自定义令牌类型
  prefix-token: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  token-base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token过期时间 此处单位/毫秒 ，默认4小时
  token-expired-time: 14400000
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  token-detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  token-restore: 3600000
  # 用户会话 id
  prefix-session-id: session-id-
  # 会话token
  prefix-session-token: session-token-
  # 开启续期 策略
  token-refresh: true
  # 剩下一小时内自动刷新
  token-refresh-scope: 3600
  # jwt证书 rsa密钥
  rsa-secret: 123456
  # logout url
  logout-url: http://localhost:8888/oauth/logout
  # 白名单URI
  ignore-uri:
    # swagger 文档
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars/**
    - /**/api-docs
    # 静态资源
    - /*.html
    - /**/*.html
    - /**/*.css
    - /**/*.js
    - /webSocket/**
    - /avatar/**
    - /file/**
    # 阿里巴巴监控
    - /druid/**
    # 安全配置接口
    - /security/**
    - /oauth/code

#公用缓存配置
cache:
  # 设置并发级别为，并发级别是指可以同时写缓存的线程数
  concurrency-level: 8
  # 设置缓存容器的初始容量为10
  initial-capacity: 10
  # 最大缓存 超过之后就会按照LRU最近虽少使用算法来移除缓存项
  maximum-size: 1000
  # 写入后缓存过期时间 分钟
  expire-alter-write: 60
  # key前缀，不同服务最好设置不同key，避免全部删除缓存
  key-prefix: cache-

#公用RSA密钥
rsa:
  private-key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==
  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANL378k3RiZHWx5AfJqdH9xRNBmD9wGD2iRe41HdTNF8RUhNnHit5NpMNtGL0NPTSSpPjjI1kJfVorRvaQerUgkCAwEAAQ==

#公用ASE密钥
aes:
  key: 1234567890ABCDEF
  iv: TRYTOCN394402133

#公用第三方服务接口
ip.region:
  base-url: https://opendata.baidu.com/api.php?&format=json&resource_id=6006&query=