spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    timeout: 5000
    mode: single
    jedis:
      pool:
        max-wait: 10
        max-active: 32
        min-idle: 2